### ISSUE TITLE
set_transaction fail, 50004

### ISSUE THREAD

**Issue by mcfang** [oipwg/js-oip#10]
Hi, guys. When use sendTx() method of js-oip sdk to send transaction. Sometimes success response txid, sometimes fail response error.
the error is {“error": "set_transaction fail", "code": "50004”}.
How to fix the problem?

**Comment by mcfang** [comment]
error reponse Error: Error broadcasting TX Hex: Error: Failed to broadcast TX Hex: Error: Unable to broadcastRawTransaction: 400 Bad Request | Verification failure: insufficient priority (code=insufficientfee score=0 hash=fc9b859d94a3e85f73d58109886f80f7fad0dc2416a8f19adf32dbd345b0a560). Code:-32603
at ExplorerWallet.sendTx (/Users/mc/node_json_rpc/node_modules/js-oip/lib/modules/wallets/ExplorerWallet.js:637:13)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
set_transaction error

**Comment by mcfang** [comment]
set_transaction(wif, address, value){
let explorer = new Insight("https://livenet.flocha.in/api");
var explprerWallet = new ExplprerWallet({ network: 'mainnet', wif: wif });
var output = {
address: address,
value: 1e8*value
}
var data;
var promise = new Promise((resolve, reject)=>{
explprerWallet.sendTx(output, '')
.then(result => {
data = result;
resolve(data)
})
.catch(err=>{
console.log(err);
console.log("set_transaction error");
reject(err)
})
})
return promise
},

this is my code

**Comment by orpheus** [comment]
You have many mispellings and irrelevant code. Shouldn't need to create your own Insight instance.
If you're using [babel](https://babeljs.io/), you can use `async/await` like this.

I recommend doing this.
```
let wallet = new ExplorerWallet( { wif: 'yourWif', network: 'mainnet' } )
let output = { address: 'addressHere', value: 'valueHereAsNumber' }
wallet.sendTx( output ).then( function (txid) {
    console.log('txid: ', txid)
}).catch( function (err) {
    console.error(err)
}) 
```

But to more accurately mimic your scenario:
```
      function set_tx (wif, address, value, network) {
        let wallet = new ExplorerWallet({ wif, network })
        let output = { address, value }
        return wallet.sendTx(output)
      }
```
